{
 "title": "General Metrics - .NET",
 "description": "Shows ASP.NET (Core/5/6/7) metrics from OpenTelemetry NuGet",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "exported_job",
    "label": "Job",
    "query": {
     "query": "label_values(multitenantapp_target_info{},exported_job)"
    }
   },
   {
    "name": "exported_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(multitenantapp_target_info{ exported_job=~\"$exported_job\"},exported_instance)"
    }
   },
   {
    "name": "http_route",
    "label": "Route",
    "query": {
     "query": "label_values(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances by Job",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(exported_job) (multitenantapp_target_info{})",
       "legendFormat": "{{exported_job}}"
      }
     ]
    },
    {
     "title": "VCPUs",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(multitenantapp_dotnet_process_cpu_count{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by( exported_job) (irate(multitenantapp_dotnet_process_cpu_time_seconds_total{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg (max_over_time(multitenantapp_dotnet_process_memory_working_set_bytes{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))by (exported_job)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Thread Pool Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  (\nmax_over_time(multitenantapp_dotnet_thread_pool_thread_count_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (exported_job)",
       "legendFormat": "{{service_osdescription}}"
      }
     ]
    },
    {
     "title": "Thread Pool Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(multitenantapp_dotnet_thread_pool_queue_length_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (exported_job)",
       "legendFormat": "{{service_osdescription}}"
      }
     ]
    },
    {
     "title": "Thread Pool Work Item Count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (\nmax_over_time(multitenantapp_dotnet_thread_pool_work_item_count_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (exported_job)",
       "legendFormat": "{{service_osdescription}}"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (generation) (\nidelta(multitenantapp_dotnet_gc_collections_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Generations (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (generation) (max_over_time(multitenantapp_dotnet_gc_heap_allocated_bytes_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Fragmentation (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (generation) (\nmax_over_time(multitenantapp_dotnet_gc_last_collection_heap_fragmentation_size_bytes {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (instance) (max_over_time(multitenantapp_dotnet_gc_last_collection_memory_committed_size_bytes {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "Committed Memory Size"
      },
      {
       "expr": "avg by (instance) (max_over_time(multitenantapp_process_runtime_dotnet_gc_objects_size{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "Objects Size"
      },
      {
       "expr": "avg by (instance) (irate(multitenantapp_process_runtime_dotnet_gc_allocations_size{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "Allocations Size"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (\nincrease(multitenantapp_dotnet_exceptions_total {exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "Exceptions"
      }
     ]
    }
   ]
  },
  {
   "title": "Kestrel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kestrel Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(multitenantapp_kestrel_active_connections{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Kestrel Queued Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(multitenantapp_kestrel_queued_connections{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Kestrel Upgraded Connections (WebSockets)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(multitenantapp_kestrel_upgraded_connections{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "Kestrel Connection Duration (Percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_kestrel_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_kestrel_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_kestrel_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Count by Method and Route",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "  sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\",http_route!~\"/internal/healthcheck|\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
       "legendFormat": "{{http_request_method}} {{http_route}}"
      }
     ]
    },
    {
     "title": "Requests Duration by Method and Route",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "  sum(increase(multitenantapp_http_server_request_duration_seconds_sum{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route!~\"/internal/healthcheck|\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
       "legendFormat": "{{http_request_method}} {{http_route}}"
      }
     ]
    },
    {
     "title": "Average Request Duration by Method and Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_sum{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) / (sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) + 0.1)",
       "legendFormat": "{{http_request_method}} {{http_route}}"
      }
     ]
    },
    {
     "title": "Error Count by Method and Route",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code!~\"2..\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
       "legendFormat": "{{http_request_method}} {{http_route}}"
      }
     ]
    },
    {
     "title": "Response Duration (Percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Response Duration Heatmap (s)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Business Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Server Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\",  exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_response_status_code) or vector",
       "legendFormat": "{{http_route}}"
      }
     ]
    },
    {
     "title": "Http Status Code Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Count by Method and Server Address",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", server_address!=\"192.168.239.18\"}[$__rate_interval])) by (http_request_method, server_address)  or vector",
       "legendFormat": "{{http_request_method}} {{server_address}}"
      }
     ]
    },
    {
     "title": "Requests Duration by Method and Route",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "  sum(increase(multitenantapp_http_client_request_duration_seconds_sum{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method, server_address) or vector",
       "legendFormat": "{{http_request_method}} {{server_address}}"
      }
     ]
    },
    {
     "title": "Average Request Duration by Method and Server Address",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_sum{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method,server_address) / (sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method,server_address) + 0.1)",
       "legendFormat": "{{http_request_method}} {{server_address}}"
      }
     ]
    },
    {
     "title": "Request Duration (Percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Response Duration Heatmap (s)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"192.168.239.18\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"192.168.239.18\",  exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Business Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Server Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_reques_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
       "legendFormat": "-1d"
      }
     ]
    },
    {
     "title": "Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\",  exported_instance=~\"$exported_instance\", http_response_status_code!=\"\"}[$__rate_interval])) by (http_response_status_code) or vector",
       "legendFormat": "{{http_route}}"
      }
     ]
    },
    {
     "title": "Http Status Code Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\",  exported_instance=~\"$exported_instance\",http_response_status_code=~\"2..\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\",  exported_instance=~\"$exported_instance\",http_response_status_code=~\"4..\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\",  exported_instance=~\"$exported_instance\",http_response_status_code=~\"5..\"}[$__rate_interval])) OR vector(0)",
       "legendFormat": "5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "SignalR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SignalR Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(multitenantapp_signalr_server_active_connections{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "SignalR Connection Duration (Percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_signalr_server_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_signalr_server_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_signalr_server_connection_duration_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Concurrency & Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Server Active Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(multitenantapp_http_server_active_requests{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    },
    {
     "title": "HTTP Client Time in Queue (Percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_http_client_request_time_in_queue_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_http_client_request_time_in_queue_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_http_client_request_time_in_queue_seconds_bucket{exported_job=~\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}