{
 "title": "MultiTenantApp - Metrics",
 "description": "Shows ASP.NET (Core/5/6/7) metrics from OpenTelemetry NuGet",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "deployment_environment",
    "label": "Environment",
    "query": {
     "query": "label_values(multitenantapp_target_info,deployment_environment)"
    }
   },
   {
    "name": "exported_job",
    "label": "Job",
    "query": {
     "query": "label_values(multitenantapp_target_info{deployment_environment=~\"$deployment_environment\"},exported_job)"
    }
   },
   {
    "name": "exported_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(multitenantapp_target_info{deployment_environment=~\"$deployment_environment\", exported_job=~\"$exported_job\"},exported_instance)"
    }
   },
   {
    "name": "http_route",
    "label": "Route",
    "query": {
     "query": "label_values(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances by Job",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(exported_job) (multitenantapp_target_info{deployment_environment=~\"$deployment_environment\"})",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "VCPUs",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(multitenantapp_process_cpu_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\",exported_instance=~\"$exported_instance\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by( exported_instance) (irate(multitenantapp_process_cpu_time_seconds_total{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TOTAL CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  irate(multitenantapp_process_cpu_time_seconds_total{\n    exported_job=~\"$exported_job\",\n    deployment_environment=~\"$deployment_environment\",\n    exported_instance=~\"$exported_instance\"\n  }[$__rate_interval])\n)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (max_over_time(multitenantapp_process_memory_usage_bytes{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Threads (sumby OS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum  (\nmax_over_time(multitenantapp_process_threads{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (service_osdescription)",
     "legendFormat": "{{service_osdescription}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads (sum by OS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(multitenantapp_process_runtime_dotnet_thread_pool_threads_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (service_osdescription)",
     "legendFormat": "{{service_osdescription}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length (sum by OS)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (\nmax_over_time(multitenantapp_process_runtime_dotnet_thread_pool_queue_length{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (service_osdescription)",
     "legendFormat": "{{service_osdescription}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (generation) (\nidelta(multitenantapp_process_runtime_dotnet_gc_collections_count_total{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Generations (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (generation) (max_over_time(multitenantapp_process_runtime_dotnet_gc_heap_size_bytes{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Fragmentation (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (generation) (\nmax_over_time(multitenantapp_process_runtime_dotnet_gc_heap_fragmentation_size_bytes{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "General Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (max_over_time(multitenantapp_process_runtime_dotnet_gc_committed_memory_size_bytes{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "Committed Memory Size"
    },
    {
     "expr": "avg by (instance) (max_over_time(multitenantapp_process_runtime_dotnet_gc_objects_size{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "Objects Size"
    },
    {
     "expr": "avg by (instance) (irate(multitenantapp_process_runtime_dotnet_gc_allocations_size{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "Allocations Size"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (\nincrease(multitenantapp_process_runtime_dotnet_exceptions_count_total{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Requests Count by Method and Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "  sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\",http_route!~\"/internal/healthcheck|\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests Duration by Method and Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  sum(increase(multitenantapp_http_server_request_duration_seconds_sum{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route!~\"/internal/healthcheck|\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Top Slow Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_sum{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) / (sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) + 0.1)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Server Error By Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_request_method,http_route) or vector",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Responses Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Responses Duration Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Business Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Server Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\", http_route=~\"$http_route\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\",http_route!=\"\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_response_status_code) or vector",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Http Status Code Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(multitenantapp_http_server_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\", http_route=~\"$http_route\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Requests Count by Method and Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", server_address!=\"192.168.239.18\"}[$__rate_interval])) by (http_request_method, server_address)  or vector",
     "legendFormat": "{{http_request_method}} {{server_address}}"
    }
   ]
  },
  {
   "title": "Requests Duration by Method and Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  sum(increase(multitenantapp_http_client_request_duration_seconds_sum{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method, server_address) or vector",
     "legendFormat": "{{http_request_method}} {{server_address}}"
    }
   ]
  },
  {
   "title": "Top Slow Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method,server_address) / (sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (http_request_method,server_address) + 0.1)",
     "legendFormat": "{{http_request_method}} {{server_address}}"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Responses Duration Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\",,deployment_environment=~\"$deployment_environment\",exported_instance=~\"$exported_instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"192.168.239.18\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"2..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", server_address!=\"192.168.239.18\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Business Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"4..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Server Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_reques_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code=~\"5..\"}[$__rate_interval] offset 1d) or vector(0)) / sum(rate(multitenantapp_http_client_request_duration_seconds_bucket{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\"}[$__rate_interval] offset 1d))",
     "legendFormat": "-1d"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\", http_response_status_code!=\"\"}[$__rate_interval])) by (http_response_status_code) or vector",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Http Status Code Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\",http_response_status_code=~\"2..\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\",http_response_status_code=~\"4..\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(multitenantapp_http_client_request_duration_seconds_count{exported_job=~\"$exported_job\", server_address!=\"k8s-monitori-monitori-ff06c9dc75-bbdc8e9c20d8f220.elb.us-east-1.amazonaws.com\", deployment_environment=~\"$deployment_environment\", exported_instance=~\"$exported_instance\",http_response_status_code=~\"5..\"}[$__rate_interval])) OR vector(0)",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}