//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiTenantApp.Web.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserRulesComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRulesComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiTenantApp.Web.Resources.Components.UserRulesComponent", typeof(UserRulesComponent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UserPermissions {
            get {
                return ResourceManager.GetString("UserPermissions", resourceCulture);
            }
        }
        
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        public static string PermissionType {
            get {
                return ResourceManager.GetString("PermissionType", resourceCulture);
            }
        }
        
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string AssignNewRule {
            get {
                return ResourceManager.GetString("AssignNewRule", resourceCulture);
            }
        }
        
        public static string SelectRule {
            get {
                return ResourceManager.GetString("SelectRule", resourceCulture);
            }
        }
        
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        public static string PleaseSelectRule {
            get {
                return ResourceManager.GetString("PleaseSelectRule", resourceCulture);
            }
        }
        
        public static string RuleAssignedSuccess {
            get {
                return ResourceManager.GetString("RuleAssignedSuccess", resourceCulture);
            }
        }
        
        public static string RuleRemovedSuccess {
            get {
                return ResourceManager.GetString("RuleRemovedSuccess", resourceCulture);
            }
        }
        
        public static string PermissionUpdatedSuccess {
            get {
                return ResourceManager.GetString("PermissionUpdatedSuccess", resourceCulture);
            }
        }
        
        public static string LoadingRulesError {
            get {
                return ResourceManager.GetString("LoadingRulesError", resourceCulture);
            }
        }
    }
}
